# Set the line width
# https://rust-lang.github.io/rustfmt/?version=master&search=#use_small_heuristics
use_small_heuristics = "Max"

# Re-order imports
# https://rust-lang.github.io/rustfmt/?version=master&search=#reorder_imports
reorder_imports = true

# Parser edition
# https://rust-lang.github.io/rustfmt/?version=master&search=#edition
edition = "2021"

# These options are only available in +nightly.
# group_imports = "One"
# imports_granularity = "One"
# fn_args_density = "Compressed"
# overflow_delimited_expr = "true"
